### ISSUE TITLE
Gallery don't show up when going back on it from cards page on Chrome

### ISSUE THREAD

**Issue by daviserez** [unil-lettres/dilps-tiresias#162]
Go to the home page that display the list of cards as a gallery. Navigate to a card. Return to the home page either by clicking on the browser back button or from the menu home button. The list of cards don't show up anymore.

If we had scrolled through the list, only the seconds "batch" of results will show, never the first cards.

It occurs on Chrome, but not on Firefox (not tested with other browsers).

This bug was introduced by this [commit](https://github.com/unil-lettres/dilps-tiresias/pull/160/commits/c08c3f89ac0d1597fe672f2320c0637dcb414d41).

@PowerKiKi I let you check if you want to investigate more on the problem or just revert the change.

![CleanShot 2024-07-22 at 11 32 19](https://github.com/user-attachments/assets/44fc9ab2-e332-4158-9e45-120583f3770b)

**Comment by PowerKiKi** [comment]
I had a look, and could not find the root cause.

The usage of `provideZoneChangeDetection({eventCoalescing: true})` means that DOM events might be triggered later and/or in a different order (i think?). We also saw a change of behavior in other places after that change ([and fixed it](https://github.com/Ecodev/natural/commit/41ab5cfdc9d5424b92c4ef520bfa5ceb15d39375)). But in this case I could not figure out what happened, or didn't happened. I suspect it might in `@ecodev/natural-gallery-js`, or at worst between `@ecodev/angular-natural-gallery` and `@ecodev/natural-gallery-js`, but could not pinpoint it :-/

One thing is clear though, either disabling `AppRouteReuseStrategy` or disabling events coalescing fixes the issue. So I suppose it is fine to keep event coalescing disabled and not investigate further. Because I don't think event coalescing would matter very much in the case of Dilps (where the DOM tends to be relatively simple).
